# Generated by Django 3.0.3 on 2021-04-11 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sighting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('longitude', models.FloatField(help_text='The longitude of the sight')),
                ('latitude', models.FloatField(help_text='The latitude of the sight')),
                ('unique_squirrel_id', models.CharField(help_text='The unique ID of the squirrel', max_length=16)),
                ('shift', models.CharField(blank=True, choices=[('AM', 'A.M.'), ('PM', 'P.M.')], help_text='Whether the squirrel observed in the before noon or after noon.', max_length=8)),
                ('data', models.DateField(blank=True, help_text='The date the squirrel was observed.', null=True)),
                ('age', models.CharField(blank=True, choices=[('Adult', 'Adult'), ('Juvenile', 'Juvenile'), ('Unknown', '?')], help_text='The age of the squirrel.', max_length=16)),
                ('primary_fur_color', models.CharField(blank=True, choices=[('Black', 'Black'), ('Gray', 'Gray'), ('Cinnamon', 'Cinnamon')], help_text='The fur color of the squirrel.', max_length=16)),
                ('location', models.CharField(blank=True, choices=[('Ground Plane', 'Ground Plane'), ('Above Ground', 'Above Ground')], help_text='The location of the squirrel.', max_length=128)),
                ('specific_location', models.CharField(blank=True, help_text='The additional notes to the location', max_length=128)),
                ('running', models.BooleanField(blank=True, help_text='Is running?')),
                ('chasing', models.BooleanField(blank=True, help_text='Is chasing?')),
                ('climbing', models.BooleanField(blank=True, help_text='Is climbing?')),
                ('eating', models.BooleanField(blank=True, help_text='Is eating?')),
                ('foraging', models.BooleanField(blank=True, help_text='Is foraging?')),
                ('other_activities', models.CharField(blank=True, help_text='Other Activities', max_length=128, null=True)),
                ('kuks', models.BooleanField(blank=True, help_text='Kuks')),
                ('quaas', models.BooleanField(blank=True, help_text='Quaas')),
                ('moans', models.BooleanField(blank=True, help_text='Moans')),
                ('tail_flags', models.BooleanField(blank=True, help_text='Tail flags')),
                ('tail_twitches', models.BooleanField(blank=True, help_text='Tail twitches')),
                ('approaches', models.BooleanField(blank=True, help_text='Approaches')),
                ('indifferent', models.BooleanField(blank=True, help_text='Indifferent')),
                ('runs_from', models.BooleanField(blank=True, help_text='Runs from')),
            ],
        ),
    ]
