# Generated by Django 3.0.3 on 2021-04-11 05:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sightings', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sighting',
            old_name='data',
            new_name='date',
        ),
    ]
